### ISSUE TITLE
Crash when trying to run this mod

### ISSUE THREAD

**Issue by ghost** [thundR/RedstoneRepository#1]
the mod seems to crash for no reason wenn installed .

Forge:14.23.3.2675
codechickenlib:3.1.7.340
cofhcore:4.4.0.10
RedstoneArsenal:2.4.1.7
RedstoneFlux:2.0.1.2
RedstoneRepository:0.1.1-2
ThermalExpansion:5.4.1.24
ThermalFoundation:2.4.0.14

it seems like something is wrong with the initialization .

**Comment by thundr** [comment]
Do you have a crash log? I can't help much with just that,

**Comment by thundr** [comment]
Nvm, found the problem, a new build will be up shortly.

**Comment by ghost** [comment]
good thanks.
