### ISSUE TITLE
ReRelease on curse

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [thundR/RedstoneRepository#13]
I was using this in my Questing modpack, and the pack broke when i tried to push the latest update, because this mod isnt on curse anymore. IDK why, but ... 

Also i need it because it was a major step of the gating and would hate to redo it.

Was it just a bug that it got deleted?

**Comment by thundr** [comment]
@CrankySupertoon01 I saw you reposted this mod on Curse, which I don't really mind, but I believe EpicSquid, the EIO dev, was planning on maintaining the mod from now on. You may want to check with him, because this version will not get any patches at all.

**Comment by CrankySupertoonArchive** [comment]
I will, and if he does maintain it i will transfer him overship
