### ISSUE TITLE
Mod crashes on start up

### ISSUE THREAD

**Issue by CapturedCherry-zz** [thundR/RedstoneRepository#3]
Mod will crash on start up. 
Forge version 14.23.3.2655
[crash-2018-04-28_23.39.45-client.txt](https://github.com/thundR/RedstoneRepository/files/1958259/crash-2018-04-28_23.39.45-client.txt)

**Comment by thundr** [comment]
Make sure you have the latest versions of all dependencies installed.

**Comment by thundr** [comment]
Alright I have the problem, will be fixed in next build.
EDIT: If you want to play for the time being, downgrade cofhcore to 4.4.0

**Comment by thundr** [comment]
[This version](https://ci.thundr.pw/job/RedstoneRepository/lastSuccessfulBuild/artifact/build/libs/RedstoneRepository-1.12.2-0.2.0-9-universal.jar) should fix the crash, it will be up on curse shortly. Core changed some things that had to be mitigated. This may break in the future.

**Comment by CapturedCherry-zz** [comment]
Okay Thank you for the help :)
