### ISSUE TITLE
Gelid flux Capacitor Amulet

### ISSUE THREAD

**Issue by Keridos** [thundR/RedstoneRepository#4]
The Capacitors are all placable in any bauble slot. Could you please enable that too for the Gelid one?

**Comment by thundr** [comment]
I'll think about it, but KL's questionable decisions do not necessarily warrant a change on my end. IMO just making capacitors fit in any bauble slot breaks the immersion of the baubles mod, where you should have to think about and prioritize certain slots, and gear has themed slot requirements. (E.g. botania tectonic belt can't be worn on your head.)
